---
title: "Filesystems"
author: "Presented by Trevor"
---

# 1: Intro to Filesystems

The way your computer stores information as files in an organized manner.

Stored as a tree, with folders and files.

## What is a Filesystem

- Files and Folders as a tree structure

```
> tree

/boot
├── EFI
│   ├── BOOT
│   │   └── BOOTX64.EFI
│   ├── Linux
│   ├── nixos
│   │   ├── 3wpmjs32cmbsrxdj2pn3a04hcrfyxzsj-linux-6.16.6-bzImage.efi
│   │   ├── 7kbjk7q5nyhvl6fgyygiwad84wb16jy8-initrd-linux-6.16.6-initrd.efi
│   └── systemd
│       └── systemd-bootx64.efi
└── loader
    ├── entries
    │   ├── nixos-generation-392.conf
    │   ├── nixos-generation-393.conf
    │   └── nixos-generation-394.conf
    ├── entries.srel
    ├── loader.conf
    └── random-seed
```

## Structure of a Filesystem

:::{ .center}

| |
| :-: |
| |
| Application |
| VFS |
| Page & Buffer Cache |
| Filesystem |
| LVM and RAID |
| Device Mapper |
| Partition Scheme |
| Basic Block Storage |
| I/O controller |
| Physical Devices |
| |

:::

## Purpose of Filesystems

- Permissions
- Physical Storage & RAID
- Drivers

## Filesystem Concepts

- Inodes / Dentries
- Blocks, Superblocks, Extents
- Journaling, Metadata

## In comparison to other file storage methods

- Blob Storage
- Databases

# 2: Types of Filesystems

## Traditional

- ext4
- NTFS
- ReiserFS
- HFS

## Modern

- XFS
- BtrFS
- F2FS
- APFS
- ZFS

## Network

- NFS
- SMB
- CIFS
- IPFS

## Special

- tmpfs/ramfs
- overlayfs
- squashfs
- sysfs, procfs
- lukfs/fscrypt

## Comparison

# 3: Filesystems on Linux

## Filesystems on Linux

- The VFS
- Device Block Files
- Drivers as Modules
- Mounting mechanics
- Linking

## Filesystem Tools

- mkfs
- dd
- fstab
- mount/umount
- fsck
- tune2fs
- df/du
- iotop/iostat
- (g)parted
- disko
- Stratis

# 4: Implementation Details

## Overarching Stucture

- Layers of blocks
- Journaling
- Inodes and Dentries

## Common Algorithms

- Allocation Strategies (Bitmap, Extent, B-tree)
- Garbage Collection
- Dedup and Compression
- CoW

# Sources

- https://www.cs.uic.edu/~jbell/CourseNotes/OperatingSystems/12_FileSystemImplementation.html
