---
title: "Networks"
author: "Presented by Trevor and Wolf"
---

# 1: Introduction

## What is Networking?

Networking is the way that multiple computer systems connect and exchange data.

This is performed through a 7-layer abstraction stack called the Open Systems Interconnection model.

## The Abstraction Stack

The Open Systems Interconnection Model - not a formal requirement for networking

|        Layer | Purpose                            |
| -----------: | ---------------------------------- |
|  Application | Provides networking to apps        |
| Presentation | Converts or encrypts data          |
|      Session | Manages stateful connections       |
|    Transport | Sends and Tracks packets           |
|      Network | Routing of packets across networks |
|    Data Link | Communication between two devices  |
|     Physical | Physical infrastructure            |

## Protocols

A protocol is an implementation of one layer in the stack, it also includes how data is layed out in that layer.

- HTTP, FTP, SMTP, SSH
- SSL/TLS
- RPC
- TCP, UDP
- IP, ICMP
- Ethernet, PPP
- IEEE 802.* (WiFi/Ethernet)

## Protocol Suite

Protocol Suites are sets of protocols that span multiple layers of the stack.

For example, HTTPS(TCP/IP) utilizes SSL/TLS, TCP, and IP.

```{mermaid}
graph TB
    subgraph OSI["OSI Model"]
        L7["Layer 7<br>Application"]
        L6["Layer 6<br>Presentation"]
        L4["Layer 4<br>Transport"]
        L3["Layer 3<br>Network"]
        L2["Layer 2<br>Data Link"]
        L1["Layer 1<br>Physical"]
    end

    subgraph HTTPS
      HTTP
      TLS
      TCP
      IP
    end

    L7 --> HTTP
    L6 --> TLS
    L4 --> TCP
    L3 --> IP
```

# 2: OSI Layers

## Physical

:::{.columns}
:::{.column width="25%"}
| |
| :-----: |
| |
|   App   |
|  Pres.  |
|  Sess.  |
| Transp. |
|  Netw.  |
|  Data.  |
| ***--- Phys. ---*** |
| |
:::
:::{.column width="75%"}
The physical medium that physically transports data between two devices.

Could be:

- Copper wires
- Fiber optic
- Radio
- Lasers
- Birds
:::
:::

## Data Link

:::{.columns}
:::{.column width="25%"}
| |
| :-----: |
| |
|   App   |
|  Pres.  |
|  Sess.  |
| Transp. |
|  Netw.  |
| ***--- Data. ---*** |
|  Phys.  |
| |
:::
:::{.column width="75%"}
The language that physical devices speak to each other. This is typically highly linked to the physical layer.

- Ethernet is typically spoken over multiple strands of copper
- WiFi is typically used when using radio
- PPP (Point to Point Protocol) was used for things like Dial-Up
:::
:::

## Network

:::{.columns}
:::{.column width="25%"}
| |
| :-----: |
| |
|   App   |
|  Pres.  |
|  Sess.  |
| Transp. |
| ***--- Netw. ---*** |
|  Data.  |
|  Phys.  |
| |
:::
:::{.column width="75%"}
Manages how information is addressed and sent to the correct destination, down the fastest available route

This includes:

- IP (Internet Protocol)
- PIM/IP (Protocol Indepedent Multicast)
- ICMP (Internet Control Management)
- IGMP (Internet Group Management)
- IPsec (IP Security)

:::
:::

## Transport

:::{.columns}
:::{.column width="25%"}
| |
| :-----: |
| |
|   App   |
|  Pres.  |
|  Sess.  |
| ***--- Transp. ---*** |
|  Netw.  |
|  Data.  |
|  Phys.  |
| |
:::
:::{.column width="75%"}
Manages exactly how packets are reliably sent to and from the target. Typically, only TCP (Transmossion Control) or UDP (User Datagram) are used.

Has to manage:

- Segmentation
- Flow Control
- Error / Loss
- Multiplexing
:::
:::

## Session

:::{.columns}
:::{.column width="25%"}
| |
| :-----: |
| |
|   App   |
|  Pres.  |
| ***--- Sess. ---*** |
| Transp. |
|  Netw.  |
|  Data.  |
|  Phys.  |
| |
:::
:::{.column width="75%"}
Manages keeping sessions open on devices. This ensures that ports remain open when you have an active connection. Not many protocols utilize this much anymore.

- RPC (Remote Procedure Call)
- SAP (Session Announcement)
- SIP (Session Initiation)
- Sometimes TCP/SSL

:::
:::

## Presentation

:::{.columns}
:::{.column width="25%"}
| |
| :-----: |
| |
|   App   |
| ***--- Pres. ---*** |
|  Sess.  |
| Transp. |
|  Netw.  |
|  Data.  |
|  Phys.  |
| |
:::
:::{.column width="75%"}
Manages converting data that is sent into data that is usable for applications.

Handles:

- Translation
- Encryption
- Compression
- Serialization

This includes character encoding, SSL, and MIME.
:::
:::

## Application

:::{.columns}
:::{.column width="25%"}
| |
| :-----: |
| |
| ***--- App ---*** |
|  Pres.  |
|  Sess.  |
| Transp. |
|  Netw.  |
|  Data.  |
|  Phys.  |
| |
:::
:::{.column width="75%"}
Any application that requires networking will be on this layer including meta-protocols.

:::{}
:::{.columns}
:::{.column width="50%"}
- DHCP
- BGP
- HTTP
- NTP
- LDAP
- RDP
:::
:::{.column width="50%"}
- SSH
- SMTP
- IMAP/POP
- (S)FTP
- BitTorrent
- WebRTC
:::
:::
:::

:::
:::

# 3: Linux Concepts of Networking

- Virtual Devices


# 4: Implementations of Specific Protocols

## Ethernet

:::{.columns}
:::{.column width="50%"}
Typically represented with the symbol`<···>`

Sends electrical pulses down twisted pairs.

Uses line encoding like `Manchester`, `8b/10b`, or `PAM-5` for gigabit.
:::
:::{.column width="50%"}
PUT IN IMAGE OF ETHERNET CABLE HERE
:::
:::

