project:
  output-dir: _output

toc: true
number-sections: true
  
format:
  revealjs:
    number-sections: false
    slide-number: c/t
    show-slide-number: all
    embed-resources: true
  typst: {}

execute: 
  cache: true
