---
title: CWRU Linux Club Semester Syllabus
subtitle: Fall 2025
author: CWRUnix Executive Board
format:
    typst:
        number-sections: false
---
{{< pagebreak >}}

# Contact

CampusGroups: [community.case.edu/CWRUnix/club_signup](https://community.case.edu/CWRUnix/club_signup)

Discord: [discord.gg/gsGZbJbxkU](https://discord.gg/gsGZbJbxkU)

## Executive Teaching Board

| Exec Member      | Discord Handle | Email          | Website                |
| ---------------- | -------------- | -------------- | ---------------------- |
| Trevor Nichols   | .pmis          | tln32@case.edu | github.com/tnichols217 |
| Wolf Mermelstein | 404wolf        | wsm32@case.edu | 404wolf.com            |
| Evan Harnak      | chainsawpants  | ebh58@case.edu | evaniel.bandcamp.com   |

# Semester Overview

## Meeting Times

18:15 - 21:30
Student Organization Center (West side)
Tinkham Veale Student Center

## Recommended Supplementary Materials

- Debian Handbook: [debian-beginners-handbook.arpinux.org/trixie-en/download/the_beginners_handbook.pdf](https://debian-beginners-handbook.arpinux.org/trixie-en/download/the_beginners_handbook.pdf)
- Arch Wiki: [wiki.archlinux.org](https://wiki.archlinux.org)
- Linuxize: [linuxize.com](https://linuxize.com)
- LFS: [linuxfromscratch.org](https://www.linuxfromscratch.org)

## Club Objectives

- Build a support community around Linux
- Promote open source software
- Extend the lifespan of computing device
- Teach about the philisophical aspects of the open source movement
- Secure our electronics from digital and physical threats

# Tentative Lecture Topics

## Introductory Topics

### Introduction to Linux

- What is Linux?
- The Linux and UNIX philosophy
    - "Do one thing and do it well"
- Setting up WSL on Windows / QEMU on Mac

### Distro Comparison

- Package managers across distros: `apt`, `dnf`, `pacman`, `nix`, `rpm`, etc.
- Installing and updating software
- What makes different distros different
- Why would you choose one over the other
- What are some applications of different distros

### Linux Basics

- The Structure of Linux
- Processes
- Filesystem Heirarchy (FHS)
- Namespaces
- SystemD
- SSH
- TTY and terminal emulators
- User vs. Kernel Space
- Syscalls
- Cgroups
- Environmental Variables
    - PATH
    - Library Pathes

### Scripting and Bash Essentials

- Command line basics and utilities
    - GNU coreutils / Busybox
- Bash and its derivatives
- Environment variables, pipes, redirection
- Writing simple bash scripts
- Variables, conditionals, loops
- Common conventions of scripting
- CLI Conventions
- Esoteric scripting languages
    - Nushell
    - Fish
    - JQ
    - Regex
- Python and other hihgher level languages

### Filesystems and File Mangement

- Basic Linux filesystem structure (FHS)
- File permissions (`chmod`, `chown`)
- Chroot'ing
- Mounting and navigating the filesystem
- Filesystems overview: ext4, XFS, Btrfs, ZFS
- Disk tools: `lsblk`, `fdisk`, `mount`, `df`
- FUSE
- FS structure comparison / deep dive
- Plan 9 brief rundown

### Networking, Web Servers, and Security

- Linux networking tools: `ip`, `ss`, `nmap`, etc.
- Web servers: Apache
- Reverse proxies: Nginx
- 7 Layers of the Network Stack
- PGP
- NFtables and Firewalls
- DNS Heirarchy
- Tunnels and VPNs
- BGP / BIRD routing
- Local level network switching
- Sockets and RTC
- Packets

### Desktop Linux

- Overview of DEs: GNOME, KDE, XFCE, i3
- Customizing your Linux desktop (Ricing)
- X11 vs Wayland
- XDG
- Desktop Portals
- Audio
- Common User Daemons
    - DBus
    - Notifications
    - Bluetooth
    - Pipewire

## Intermediate Topics

### Linux Tools and The Linux Boot Process

- Git basics (clone, commit, push)
- Vim basics and configuration
- Crontab and job scheduling
- Wolf's Favorite CLI tools
- GRUB and EFI
- Partitioning Tools
- Init systems
- Systemd Day
    - Services
    - Timers
    - `journalctl`
    - Mounts
    - Networkd

### Linux Security

- SELinux
- Flatpak / Bubblewrap
- Linux Hardening
- PGP / GPG / SSH
- TTOP and Yubikeys
- Common Attack Vectors
- AppArmor
- Secure Boot
- TPM, Intel ME, AMD PSP
- Memory Safety
- Containerization
- Kali Tools
- Hypervisors and microkernels
    - Firecracker microVMs

### Virtualization, VMs, and Containers

- QEMU / KVM / HyperV / Virtualization.Framework
- Wine / Proton
- Docker, Podman, nspawn
- OCI concepts
    - Runtimes
- Network File Shares
- P9FS

### Cloud, Infrastructure, and DevOps

- Cloud Hosting
    - AWS, EC2
    - Azure
- Terraform, Ansible, Pulumi, IaC
- CI/CD concepts
    - Github Actions
    - Garnix
    - Jenkins
- Orchestraion and Kubernetes
- Nix overview

## Harder Topics

### Systems Programming Day

- Compilers
- Rust
- C/C++
- Go
- Zig
- ASM
- Linking, ELFs, Libraries
- LSPs
- Build Systems
    - make / CMake
    - Cargo
    - Basil

### Nix

- Functional Concepts
- Motivation
- Modern Software Deployment
- Treating Filesystems like memory
- The Language
- The Nix Store
- Derivations
    - Closures
    - Bundlers
- Garbage Collection
- Builders
- Environments and Profiles
- Substitutes and Binary Caches
- Distributed Deployment
- Content Addressibility
- Modules, NixOS, nixpkgs
    - Anywhere
- Home-Manager and Package Management
- Packaging Software
    - The stdenv
    - mkDerivations
    - Advanced Builders
    - Nix utilities
- Flakes
- Experimental Features
    - IFD
    - Nix in Nix
    - Dynamic Derivations
    - Fetch Closure
    - Minimal Bootstrap

### Kernel and LFS Deep Dive

- Modules and drivers
- Kernel parameters
- Simple kernel module programming
- Linux From Scratch (LFS) overview
    - Custom kernels
    - Building Linux manually
